---
podman_git_repo: "https://github.com/containers/podman.git"
podman_containers_image_ref: "df7e80d2d19872b61f352a8a182ec934dc0c2346"

# Package mapping for network handlers and runtimes
podman_package_map:
  pasta: "passt"
  slirp4netns: "slirp4netns"
  crun: "crun"
  runc: "runc"

# Build tags as recommended by documentation
podman_build_tags: "seccomp apparmor"

# User for rootless configuration
podman_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
