---
podman_version: "v6.1.0"
podman_build_dir: "/tmp/podman_build"
podman_network_handler: "pasta"
podman_runtime: "crun"
podman_install_dir: "/usr/local"
podman_config_dir: "/etc/containers"
podman_policy_source_url: "https://raw.githubusercontent.com/containers/image/{{ podman_containers_image_ref }}/default-policy.json"
podman_registries_source_url: "https://raw.githubusercontent.com/containers/image/{{ podman_containers_image_ref }}/registries.conf"
