---
galaxy_info:
  author: Richard Slater
  description: "Ansible role to install pnpm."
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - pnpm
    - node
    - package-manager

dependencies: []
