---
oh_my_posh_bin_path: "/usr/local/bin/oh-my-posh"

# Upstream publishes Linux amd64 and arm64 assets only.
oh_my_posh_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"

oh_my_posh_version: "v30.6.5"

oh_my_posh_checksums:
  amd64: "sha256:079febf68932744a6c8d05179a2798bca083613275eca6de41b1efe9c82e15c8"
  arm64: "sha256:34d81d2871cd2b211878d3e31bb7c8d7c5e70088170ee526be222a2e6b843c4d"

oh_my_posh_arch: "{{ oh_my_posh_arch_map[ansible_architecture] | default('unsupported') }}"
oh_my_posh_checksum: "{{ oh_my_posh_checksums[oh_my_posh_arch] | default(omit) }}"
oh_my_posh_supported_architectures:
  - x86_64
  - aarch64
