---
uv_version: "0.12.9"
uv_platform: "x86_64-unknown-linux-gnu"
uv_download_url: "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-{{ uv_platform }}.tar.gz"
uv_checksum: "sha256:ec7a99cd05e0cd7f80243f135ce1361c76835cb0ee60055d14d20eba8eba1460"
uv_install_dir: "{{ ansible_env.HOME }}/.local/bin"
