---
- name: Install Zsh on Debian-based systems
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install Zsh on RedHat-based systems
  ansible.builtin.dnf:
    name: zsh
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Get all interactive users (excluding system users and 'nobody')
  ansible.builtin.command: >-
    awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd
  register: zsh_interactive_users
  changed_when: false

- name: Change default shell to Zsh for all interactive users (excluding 'nobody')
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  loop: "{{ zsh_interactive_users.stdout_lines }}"
  when: zsh_interactive_users.stdout_lines | length > 0

- name: Ensure all users' default shell is Zsh
  ansible.builtin.debug:
    msg: "User {{ item }} default shell set to /bin/zsh"
  loop: "{{ zsh_interactive_users.stdout_lines }}"

- name: Verify Zsh installation
  ansible.builtin.command: zsh --version
  register: zsh_version
  changed_when: false

- name: Display installed Zsh version
  ansible.builtin.debug:
    msg: "Installed Zsh version: {{ zsh_version.stdout }}"
